config/routes.rb
Rails.application.routes.draw do
  resources :groups
  resources :expenses
  get "external_expenses_index" => "expenses#external_expenses_index"
  devise_for :users

  get "search", :to => "expenses#index"

  root "expenses#grouped_expenses_index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/expense.rb
class Expense < ApplicationRecord
  belongs_to :author, class_name: 'User'

  has_many :group_expenses
  has_many :groups, through: :group_expenses

  scope :grouped, -> { includes(:groups).where.not(groups: { id: nil }).order('expenses.created_at DESC') }
  scope :ungrouped, -> { where.missing(:groups).order('expenses.created_at DESC') }
  scope :total, -> { sum(:amount) }

  validates :author_id, presence: true
  validates :name, presence: true
  validates :amount, presence: true, numericality: { only_float: true }
end

app/models/group.rb
class Group < ApplicationRecord
  belongs_to :user

  has_many :group_expenses, dependent: :destroy
  has_many :expenses, through: :group_expenses

  has_one_attached :image

  validates :name, presence: true
  validates :user_id, presence: true

  scope :alphabetical, -> { order('name ASC') }
end

app/models/group_expense.rb
class GroupExpense < ApplicationRecord
  belongs_to :expense, dependent: :destroy
  belongs_to :group
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :expenses, foreign_key: :author_id
  has_many :groups

  validates :name, presence: true
  validates :email, presence: true
  validates :password, presence: true
  validates :password_confirmation, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[name email password password_confirmation])
  end

  private

  def after_sign_out_path_for(_resource_or_scope)
    user_session_path
  end
end

app/controllers/expenses_controller.rb
class ExpensesController < ApplicationController
  before_action :set_expense, only: %w[show edit update destroy]

  # GET /expenses
  # GET /expenses.json
  def grouped_expenses_index
    @expenses = current_user.expenses.grouped
  end

  def external_expenses_index
    @expenses = current_user.expenses.ungrouped
  end

  # GET /expenses/new
  def new
    @expense = current_user.expenses.build
  end

  # GET /expenses/1/edit
  def edit; end

  # POST /expenses
  # POST /expenses.json
  def create
    @expense = current_user.expenses.build(expense_params)

    respond_to do |format|
      if @expense.save
        format.html { redirect_to :root, notice: 'Expense was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /expenses/1
  # PATCH/PUT /expenses/1.json
  def update
    respond_to do |format|
      if @expense.update(expense_params)
        format.html { redirect_to @expense, notice: 'Expense was successfully updated.' }
        format.json { render :show, status: :ok, location: @expense }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @expense.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /expenses/1
  # DELETE /expenses/1.json
  def destroy
    @expense.destroy
    respond_to do |format|
      format.html { redirect_to :root, notice: 'Expense was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_expense
    @expense = Expense.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def expense_params
    params.require(:expense).permit(:author_id, :name, :amount, group_ids: [])
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :set_group, only: %w[show edit update destroy]

  # GET /groups
  # GET /groups.json
  def index
    @groups = current_user.groups.alphabetical
  end

  # GET /groups/1
  # GET /groups/1.json
  def show; end

  # GET /groups/new
  def new
    @group = current_user.groups.build
  end

  # GET /groups/1/edit
  def edit; end

  # POST /groups
  # POST /groups.json
  def create
    @group = current_user.groups.build(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to groups_path, notice: 'Group was successfully created.' }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { render :show, status: :ok, location: @group }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    # @group.expenses.destroy_all
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url, notice: 'Group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_group
    @group = Group.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def group_params
    params.require(:group).permit(:user_id, :name, :image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def logout_link
    link_to 'Logout', destroy_user_session_path, method: :delete, class: 'py-1 w-full' if user_signed_in?
  end

  def login_link
    link_to 'Login', new_user_session_path, class: 'px-3 py-1' unless user_signed_in?
  end

  def register_link
    link_to 'Register', new_user_registration_path, class: 'px-3 py-1' unless user_signed_in?
  end
end

app/helpers/expenses_helper.rb
module ExpensesHelper
  def most_recent_expenses(expenses)
    expenses.order('expenses.created_at DESC')
  end

  def display_existing_image(expense)
    return render partial: 'expense_image', locals: { expense: expense } unless expense.groups.first.nil?
  end
end

app/helpers/group_expenses_helper.rb
module GroupExpensesHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
  def display_group_image(group)
    render partial: 'group_image', locals: { group: group } if group.image.attached?
  end
end

app/views/expenses/_add_button.html.erb
<div class="text-center">
  <button class="bg-green-500 px-4 py-2 shadow-md rounded-md text-gray-100 m-4">
    <%= link_to "Add new", new_expense_path %>
  </button>
</div>

app/views/expenses/_display_expense.html.erb
<div class="flex p-10 flex-col">
  <div class="py-2">
    <strong>Name:</strong>
    <%= @expense.name %>
  </div>
  <div class="py-2">
    <strong>Amount:</strong>
    <%= @expense.amount %>
  </div>
</div>

app/views/expenses/_expense_image.html.erb
<div class="w-20">
  <%= image_tag(expense.groups.first.image, class: "w-full" ) if expense.groups.first.image.attached? %>
</div>

app/views/expenses/_form.html.erb
<%= form_with(model: expense) do |form| %>
  <% if expense.errors.any? %>
    <div id="error_explanation" class="text-center py-2 px-8 bg-red-500 text-gray-100">
      <ul>
        <% expense.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field flex flex-col px-8 text-center ">
    <%= form.label 'Expense name', class: "py-1 text-lg" %>
    <%= form.text_field :name %>
  </div>

  <div class="field flex flex-col px-8 py-4 text-center">
    <%= form.label :amount, class: "py-1 text-lg" %>
    <%= form.text_field :amount %>
  </div>

  <div class="control px-8">
    <%= form.label "Groups" %>
    <div class="grid grid-cols-3">
    <%= form.collection_check_boxes(:group_ids, current_user.groups.alphabetical, :id, :name) do |checkbox| %>
      <div>
        <%= checkbox.check_box %>
        <%= checkbox.label %>
      </div>
    <% end %>
    </div>
  </div>

  <div class="actions text-center pt-8">
    <%= form.submit "Submit", class: "cursor-pointer bg-blue-500 rounded-md text-gray-50 py-2 px-4" %>
  </div>
  <div class="text-center py-4">
    <%= link_to 'Back', :back, class: "border shadow-md border-green-500 text-green-500 px-4 py-1 rounded"%>
  </div>
<% end %>

app/views/expenses/_group_fields.html.erb
<div class="nested-fields">
  <%= form.hiddden_field :_destroy %>
  <div>
    <%= form.label :name %>
    <%= form.collection_select :name %>
  </div>

  <div>
    <%= link_to "Remove", '#', class: "remove_fields" %>
  </div>
</div>

app/views/expenses/_recent_expenses.html.erb
<% most_recent_expenses(expenses).each do |expense| %>
  <%= link_to expense do %>
    <div class="flex p-3 m-2 bg-white shadow rounded font-semibold">
      <%= display_existing_image(expense) %>
      <div class="flex flex-col justify-between w-full pl-3 pt-2">
        <div class="flex justify-between">
          <p class="text-gray-400"><%= expense.name %></p>
          <p class="text-gray-700">$<%= '%.2f' % expense.amount %></p>
        </div>
        <p class="text-xs text-gray-400"><%= expense.created_at.strftime("%d %b %Y") %></p>
      </div>
    </div>
    <% end %>
<% end %>

app/views/expenses/_total_expenses.html.erb
<div class="flex justify-between shadow bg-white p-4">
  <h2 class="text-lg">Total</h2>
  <p class="text-lg font-semibold">$<%= @expenses.total %></p>
</div>

app/views/expenses/edit.html.erb
<%= content_for(:title, "Edit Expense") %>
<h1 class="text-center text-3xl py-4 bg-white"><%= yield(:title) %></h1>

<%= render 'form', expense: @expense %>

app/views/expenses/external_expenses_index.html.erb
<%= content_for(:title, "External Expenses") %>
<h1 class="text-center text-3xl py-4 bg-white"><%= yield(:title) %></h1>

<%= render "total_expenses" %>

<%= render partial: "recent_expenses", locals: {expenses: @expenses} %>

<%= render "shared_partials/add_button" %>

app/views/expenses/grouped_expenses_index.html.erb
<%= content_for(:title, "All Expenses") %>
<h1 class="text-center text-3xl py-4 bg-white"><%= yield(:title) %></h1>

<%= render "total_expenses" %>

<%= render partial: "recent_expenses", locals: { expenses: @expenses.includes([:group_expenses])} %>

<%= render "shared_partials/add_button" %>

app/views/expenses/new.html.erb
<%= content_for(:title, "New Expense") %>
<h1 class="text-center text-3xl py-4 bg-white"><%= yield(:title) %></h1>

<%= render 'form', expense: @expense %>

app/views/expenses/show.html.erb
<%= render 'display_expense' %>

<div class="flex justify-evenly text-gray-50">
  <%= link_to 'Edit', edit_expense_path(@expense), class: "bg-green-500 shadow-md px-4 py-1 rounded" %> 
  <%= link_to 'Delete', @expense, class: "bg-red-600 shadow-md px-4 py-1 rounded", method: :delete, data: { confirm: 'Are you sure?' } %>
  <%= link_to 'Back', :root, class: "border shadow-md border-green-500 text-green-500 px-4 py-1 rounded"%>
</div>

app/views/groups/_create_button.html.erb
<div class="text-center">
  <button class="bg-green-500 px-4 py-2 shadow-md rounded-md text-gray-100 m-4">
    <%= link_to "Create new", new_group_path %>
  </button>
</div>

app/views/groups/_display_groups.html.erb
<% @groups.with_attached_image.each do |group| %>
  <%= link_to group do %>
  <div class="flex p-3 m-2 bg-white shadow rounded font-semibold">
    <%= display_group_image(group) %>
    <div class="flex justify-between w-full">
    
      <div class="flex flex-col justify-between h-20 pl-3">
        <p class="text-gray-400"><%= group.name %></p>
        <p class="text-xs text-gray-400"><%= group.created_at.strftime("%d %b %Y") %></p>
      </div>
        <div class="text-gray-50 self-end">
          <%= link_to 'Edit', edit_group_path(group), class: "bg-blue-500 px-4 py-1 rounded" %>
          <%= link_to 'Delete', group, class: "bg-red-600 px-4 py-1 rounded", method: :delete, data: { confirm: 'Are you sure?' } %>
        </div>
    </div>
  </div>
  <% end %>
<% end %>

app/views/groups/_form.html.erb
<%= form_with(model: group) do |form| %>
  <% if group.errors.any? %>
    <div id="error_explanation" class="text-center py-2 bg-red-500 text-gray-100">
      <ul>
        <% group.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field flex flex-col px-8 py-4 text-center">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field flex flex-col px-8 pt-4  items-center text-center">
    <%= form.label :image, id: "pictureInput", class: "rounded-lg border-2 border-gray-400 cursor-pointer px-4 py-2 " do %>
      Upload image
      <%= form.file_field :image, class: "flex flex-col hidden" %>
    <% end %>
    <div id="target" class="py-8 w-24 flex justify-center">
      <%= display_group_image(@group) %>
    </div>
  </div>

  <div class="actions text-center ">
    <%= form.submit "Submit", class: "bg-blue-500 rounded text-gray-50 py-2 px-4 cursor-pointer" %>
  </div>
  <div class="text-center py-4">
    <%= link_to 'Back', groups_path, class: "border shadow-md border-green-500 text-green-500 px-4 py-1 rounded"%>
  </div>
<% end %>

app/views/groups/_group_image.html.erb
<div class="w-20">
  <%= image_tag(group.image, class: "w-full" ) %>
</div>

app/views/groups/_grouped_expenses.html.erb
<div class="flex justify-between shadow bg-white p-4">
  <h2 class="text-lg">Total</h2>
  <p class="text-lg font-semibold">$<%= @group.expenses.total %></p>
</div>

<% @group.expenses.each do |expense| %>
  <%= link_to expense_path(expense) do %>
  <div class="flex p-3 m-2 bg-white shadow rounded font-semibold">
    <%= display_group_image(@group) %>
      <div class="flex flex-col justify-between w-full pl-3 pt-2">
        <div class="flex justify-between">
          <p class="text-gray-400"><%= expense.name %></p>
          <p class="text-gray-700">$<%= '%.2f' % expense.amount %></p>
        </div>
        <div class="flex flex-row justify-between text-xs text-gray-400">
          <p><%= expense.created_at.strftime("%d %b %Y") %></p>
          <p>Created by <%= current_user.name %></p>
        </div>
      </div>
  </div>
  <% end %>
<% end %>

app/views/groups/edit.html.erb
<%= content_for(:title, "Edit Group") %>
<h1 class="text-center text-3xl py-4 bg-white"><%= yield(:title) %></h1>

<%= render 'form', group: @group %>

app/views/groups/index.html.erb
<%= content_for(:title, "Groups") %>
<h1 class="text-center text-3xl py-4 bg-white"><%= yield(:title) %></h1>

<%= render "display_groups" %>

<%= render 'create_button' %>

app/views/groups/new.html.erb
<%= content_for(:title, "New Group") %>
<h1 class="text-center text-3xl py-4 bg-white"><%= yield(:title) %></h1>

<%= render 'form', group: @group %>

app/views/groups/show.html.erb
<%= content_for(:title, "#{@group.name} Expenses") %>
<h1 class="text-center text-3xl py-4 bg-white"><%= yield(:title) %></h1>

<%= render 'grouped_expenses' %>

<div class="text-center">
  <%= render "shared_partials/add_button" %>
  <%= link_to 'Back', groups_path, class: "border shadow-md border-green-500 text-green-500 px-6 py-1 rounded"%>
</div>

app/views/layouts/_navbar.html.erb
<nav >
  <div class="bg-blue-500 flex justify-between items-center p-2">
    <button id="nav-btn" class="text-white rounded nav-toggler" >
      <i  class="material-icons">menu</i>
    </button>
    <%= link_to :root do %>
      <%= image_tag('floop.png', class: "w-20 h-full") %>
    <% end %>
    <i class="material-icons text-white">search</i>
  </div>
  <div id="nav-links" class="hidden" >
    <div class="flex flex-col items-center text-center">
      <%= link_to "Expenses", :root, class: "py-1 w-full" %>
      <%= link_to "External expenses", external_expenses_index_path, class: "py-1 w-full" %>
      <%= link_to "Groups", groups_path, class: "py-1 w-full" %>
      <%= logout_link %>
      <%= login_link %>
      <%= register_link %>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= yield(:title) %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="bg-gray-100">
    <%= render "layouts/navbar" %>
    <% if flash[:notice] %>
      <p class="notice text-center py-2 bg-green-500 text-gray-100"><%= flash[:notice] %></p>
    <% end %>
    <% if flash[:alert] %>
      <p class="alert text-center py-2 bg-red-500 text-gray-100"><%= alert %></p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/shared_partials/_add_button.html.erb
<div class="text-center">
  <button class="bg-green-500 px-4 py-2 shadow-md rounded-md text-gray-100 m-4">
    <%= link_to "Add new", new_expense_path %>
  </button>
</div>

app/views/shared_partials/_search_bar.html.erb
<%= form_tag(search_path, :method => "get", :class=>"form-inline my-2 my-lg-0") do %>
  <%= text_field_tag :search, params[:search], placeholder: "Search Articles", class: "form-control" %>

  <span class="input-group-btn">
    <%= submit_tag "Search", class: '' %>
  </span>
<% end %>